name: Scanner

on:
  issues:
    types:
      - opened

jobs:
  scan:
    name: Scan container Images
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_URL: ${{ github.event.issue.html_url }}
      ISSUE_BODY: ${{ github.event.issue.body }}
    
    steps:
      - name: Init
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          # Install trivy
          sudo apt-get install trivy  

      # TASK/TODO: 
      # Build this step in the workflow. Refer to the linked document in the README for more details
      - name: TODO - Scan Vulnerabilities
        run: echo "Build this step in the workflow. Refer to the linked document in the README for more details"

      - name: View issue information
        run: |
          echo "${{ github.event.issue.body }}" | tr -d "[]" | tr -s "," "\n" | tac > newscan.txt
          input=newscan.txt

          while IFS= read -r image
          do
                  trivy image --security-checks vuln --format template --quiet --exit-code 1 "$image"
                  status=$(echo $?)
                  if [ "$status" -eq 0 ]; then safety="SAFE"; else safety="UNSAFE"; fi
                  echo "\"image\": \"$image\""
                  echo "\"status\": \"$safety\""
          done < "$input"